#!/bin/bash

for movie in ~/Videos/s9/*; do
	exit_status=$(mpv --save-position-on-quit "$movie" | tail -n 1)
	if [ "$exit_status" == "Exiting... (End of file)" ]; then
		rm "$movie"
		if [ "$(find ~/Videos/s9 -mindepth 1)" != "" ]; then
			echo "Do you want to see the next episode(y/n)?"; read input
			while [[ $input != "y" && $input != "n" ]]; do
				echo "Please enter y or n"; read input
			done
			case $input in
				"y")
				continue
				;;
				"n")
				break
			esac
		else
			rmdir ~/Videos/s9
		fi
	else
		break
	fi
done


